apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appointment-service
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appointment-service
  strategy: {}
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - image: ahhmedhs/project-appointment-service
          name: appointment-service
          ports:
            - containerPort: 8060
      hostname: localhost
      restartPolicy: Always
