apiVersion: v1
kind: Service
metadata:
  labels:
    app: appointment-service
  name: appointment-service
spec:
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8060
  selector:
    app: appointment-service
