apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8070
  selector:
    app: chat-service
