apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email-service
spec:
  ports:
    - name: "8075"
      port: 8075
      targetPort: 8075
  selector:
    app: email-service
