apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: user-service
